version: '3.5'

services:

  uqam-station-dev:
    container_name: uqam-station-dev
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    volumes:
      - ../../:/var/www/station.escer.uqam.ca
      - ../../resources:/var/www/station.escer.uqam.ca/media
    command: python manage.py runserver 0.0.0.0:80
    networks:
      sitewebrecherche:
        ipv4_address: 172.20.0.7

networks:
  sitewebrecherche:
    external: true
