# Generated by Django 2.1.12 on 2019-09-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidite', models.FloatField(blank=True, null=True)),
                ('pression', models.FloatField(blank=True, null=True)),
                ('directionvent', models.FloatField(blank=True, db_column='directionVent', null=True)),
                ('vitessevent', models.FloatField(blank=True, db_column='vitesseVent', null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('pyranometre', models.FloatField(blank=True, null=True)),
                ('pyranometreup', models.FloatField(blank=True, db_column='pyranometreUP', null=True)),
                ('pyranometredw', models.FloatField(blank=True, db_column='pyranometreDW', null=True)),
                ('pyregeometreup', models.FloatField(blank=True, db_column='pyregeometreUP', null=True)),
                ('pyregeometredw', models.FloatField(blank=True, db_column='pyregeometreDW', null=True)),
                ('electerre', models.FloatField(blank=True, db_column='elecTerre', null=True)),
                ('prec1mm', models.FloatField(blank=True, null=True)),
                ('prec2mm', models.FloatField(blank=True, null=True)),
                ('prec3mm', models.FloatField(blank=True, null=True)),
                ('prec1tot', models.FloatField(blank=True, null=True)),
                ('prec2tot', models.FloatField(blank=True, null=True)),
                ('prec3tot', models.FloatField(blank=True, null=True)),
                ('precmoy', models.FloatField(blank=True, null=True)),
                ('precmoytot', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ReleveMeteo',
                'managed': False,
            },
        ),
    ]
