version: '3.5'

services:

  uqam-station:
    container_name: uqam-station
    build:
      context: ../
      dockerfile: docker/Dockerfile

    volumes:
      - '../:/usr/uqam-station-website'
    networks:
      sitewebrecherche:
        ipv4_address: 172.18.0.7

networks:
  sitewebrecherche:
    external: true
