version: '3.5'

services:

  uqam-station:
    container_name: uqam-station
    build:
      context: ../
      dockerfile: docker/Dockerfile

    networks:
      riisqdocker_default:
        ipv4_address: 172.23.0.6

#    volumes:
#      - ../:/usr/uqam_station_website

networks:
  riisqdocker_default:
    external: true