version: '3.5'

services:

  uqam-station:
    container_name: uqam-station
    build:
      context: ../
      dockerfile: docker/Dockerfile
    networks:
      sitewebrecherche:
        ipv4_address: 172.20.0.7

networks:
  sitewebrecherche:
    external: true
