version: '3.5'

services:

  uqam-station-prod:
    container_name: uqam-station-prod
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    volumes:
      - ../../resources:/var/www/station.escer.uqam.ca/media
    networks:
      sitewebrecherche:
        ipv4_address: 172.20.0.7

networks:
  sitewebrecherche:
    external: true
