version: '3.5'

services:

  uqam-station-prod:
    container_name: uqam-station-prod
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    networks:
      sitewebrecherche:
        ipv4_address: 172.18.0.7

networks:
  sitewebrecherche:
    external: true
