version: '3.5'

services:

  web:
    container_name: uqam-station
    build:
      context: ../../
      dockerfile: docker/deployment/Dockerfile
    volumes:
      - static_volume:/var/www/station.escer.uqam.ca/staticfiles
    command: gunicorn -c config/gunicorn/gunicorn.production.conf
      --env DJANGO_SETTINGS_MODULE=uqam_station_website.settings.production
      --bind 0.0.0.0:8000 uqam_station_website.wsgi
    expose:
      - 8000
    networks:
      sitewebrecherche:
        ipv4_address: 172.18.0.8

  nginx:
    container_name: nginx-uqam-station
    depends_on:
      - web
    build:
      context: ../../
      dockerfile: docker/production/nginx.Dockerfile
    volumes:
      - static_volume:/var/www/station.escer.uqam.ca/staticfiles
    networks:
      sitewebrecherche:
        ipv4_address: 172.18.0.7

networks:
  sitewebrecherche:
    external: true

volumes:
  static_volume:
